set(TARGET minslm)
add_executable(${TARGET} minslm.cpp slminfer.cpp)
install(TARGETS ${TARGET} RUNTIME)
target_include_directories(minslm PUBLIC .)
target_include_directories(minslm PUBLIC ../..)
target_include_directories(minslm PUBLIC ../../common)
target_link_libraries(${TARGET} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_11)
include_directories(${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR})
